export const Genre = {
  ACTION: "ACTION",
  ADVENTURE: "ADVENTURE",
  RPG: "RPG",
  STRATEGY: "STRATEGY",
  SIMULATION: "SIMULATION",
  SPORTS: "SPORTS",
  PUZZLE: "PUZZLE",
  HORROR: "HORROR",
  PLATFORMER: "PLATFORMER",
  SHOOTER: "SHOOTER",
  RACING: "RACING",
  FIGHTING: "FIGHTING",
  MMO: "MMO",
  SANDBOX: "SANDBOX",
  SURVIVAL: "SURVIVAL",
  RHYTHM: "RHYTHM",
  EDUCATIONAL: "EDUCATIONAL",
  CASUAL: "CASUAL",
  INDIE: "INDIE",
  MOBA: "MOBA",
  FPS: "FPS"
} as const;

export type Genre = (typeof Genre)[keyof typeof Genre];

